### ISSUE TITLE
Test settings of OadTR.

### ISSUE THREAD

**Issue by sqiangcao99** [wangxiang1230/OadTR#13]
Hi, thanks for your amazing work. When testing the performance of OadTR, I found you seem to miss the first few frames of the video. This may be unfair compared to other methods.

**Comment by wangxiang1230** [comment]
> Hi, thanks for your amazing work. When testing the performance of OadTR, I found you seem to miss the first few frames of the video. This may be unfair compared to other methods.

Hi, there is a chance of error in this case, but generally the test video is very long, and these errors can be very small. And IDN (CVPR2020) is also this way of testing.
