### ISSUE TITLE
fps of the original video

### ISSUE THREAD

**Issue by Wangjh0125** [wangxiang1230/OadTR#18]
Hi
Thank you for sharing the dataset. But I met some problems when I used the dataset. As you said in the previous issue, the fps of the origin video is 24fps, so the actual fps of the feature is 4, but I calculate the frames and the seconds of the video found that the fps of the feature is 5... If there is any mistakes?

**Comment by wangxiang1230** [comment]
> Hi Thank you for sharing the dataset. But I met some problems when I used the dataset. As you said in the previous issue, the fps of the origin video is 24fps, so the actual fps of the feature is 4, but I calculate the frames and the seconds of the video found that the fps of the feature is 5... If there is any mistakes?

Thanks for your attention to OadTR. We extract video frames at the original frame rate of the video, and extract a feature every 6 frames. Each video may vary from 24FPS to 30FPS. In the experiment, we also found that the frame rate has little effect on the final result (e.g., 24FPS vs. 30FPS), a very simple way to verify is that you can linearly interpolate all the features to the 24FPS video input, and then compare their performance. It should be noted that the label shape also needs to be resized accordingly.
