### ISSUE TITLE
Can I get pretrained model?

### ISSUE THREAD

**Issue by jun297** [wangxiang1230/OadTR#33]
Unfortunately, zenodo links are all broken..
I want to check whether the model trained well

Could you upload it on google drive as well please?
Thank you in advance

**Comment by wangxiang1230** [comment]
> Unfortunately, zenodo links are all broken.. I want to check whether the model trained well
> 
> Could you upload it on google drive as well please? Thank you in advance


Hi, the checkpoint file is [here](https://drive.google.com/file/d/1tb7JuvZJXsKuS9MGzUAP886lSlnlHeCX/view?usp=sharing).

**Comment by jun297** [comment]
Thanks a lot!
