### ISSUE TITLE
Excuse me, The download link for "The preprocess file for HDD is here. The code of the network is here." is broken

### ISSUE THREAD

**Issue by wssxjtu** [wangxiang1230/OadTR#34]

**Comment by wangxiang1230** [comment]
Hi, we have updated the [link](https://drive.google.com/file/d/19TO4sFNHDwUPPRcdG2jPc97nEeWRMY9a/view?usp=sharing). The shared ZIP file includes the dataset file, network file, and sensor data of HDD. Thanks.

**Comment by wssxjtu** [comment]
> Hi, we have updated the [link](https://drive.google.com/file/d/19TO4sFNHDwUPPRcdG2jPc97nEeWRMY9a/view?usp=sharing). The shared ZIP file includes the dataset file, network file, and sensor data of HDD. Thanks.

Thank you very much for your reply, can you share the config.py for HDD please?

**Comment by wangxiang1230** [comment]
> > Hi, we have updated the [link](https://drive.google.com/file/d/19TO4sFNHDwUPPRcdG2jPc97nEeWRMY9a/view?usp=sharing). The shared ZIP file includes the dataset file, network file, and sensor data of HDD. Thanks.
> 
> Thank you very much for your reply, can you share the config.py for HDD please?

Hi, the config file for HDD is [here](https://drive.google.com/file/d/1uIK9i3HrxPHidLrw1wQ6lNCgPqTUWDK1/view?usp=sharing).

**Comment by wssxjtu** [comment]
> > > Hi, we have updated the [link](https://drive.google.com/file/d/19TO4sFNHDwUPPRcdG2jPc97nEeWRMY9a/view?usp=sharing). The shared ZIP file includes the dataset file, network file, and sensor data of HDD. Thanks.
> > 
> > 
> > Thank you very much for your reply, can you share the config.py for HDD please?
> 
> Hi, the config file for HDD is [here](https://drive.google.com/file/d/1uIK9i3HrxPHidLrw1wQ6lNCgPqTUWDK1/view?usp=sharing).

Thank you very much for your reply, your response will help me a lot!
Good luck with your work!
