### ISSUE TITLE
TVSeries anno link

### ISSUE THREAD

**Issue by ManuBenavent** [wangxiang1230/OadTR#35]
> Hi,
> 
> Could you please provide the label set of TVseries dataset. The actions have less duration. I hope to align with your setup in this dataset.

Hi, thanks for your attention to OadTR. You can get anno files and preprocessing file [Here](https://zenodo.org/record/5266372#.YSc910vitPY).

_Originally posted by @wangxiang1230 in https://github.com/wangxiang1230/OadTR/issues/5#issuecomment-906153557_
            

hi, thanks for your amazing work!
When I opened the download link with anno files and preprocessing file, it displayed the message: "Gone! The record you are trying to access was removed from Zenodo. The metadata of the record is kept for archival purposes. Reason for removal: Spam record, removed by Zenodo staff."
Could you please provide the download link again?

**Comment by wangxiang1230** [comment]
> ```
>           > Hi,
> ```
> 
> > Could you please provide the label set of TVseries dataset. The actions have less duration. I hope to align with your setup in this dataset.
> 
> Hi, thanks for your attention to OadTR. You can get anno files and preprocessing file [Here](https://zenodo.org/record/5266372#.YSc910vitPY).
> 
> _Originally posted by @wangxiang1230 in [#5 (comment)](https://github.com/wangxiang1230/OadTR/issues/5#issuecomment-906153557)_
> 
> hi, thanks for your amazing work! When I opened the download link with anno files and preprocessing file, it displayed the message: "Gone! The record you are trying to access was removed from Zenodo. The metadata of the record is kept for archival purposes. Reason for removal: Spam record, removed by Zenodo staff." Could you please provide the download link again?


Hi, thanks for your attention. The annotation files for TVseries dataset is [here](https://drive.google.com/file/d/1izK7qfIUq57uefv3Sut0jPSuWfw8ikD_/view?usp=sharing).
